export const queryKeys = {
  profile: (userId: string) => ["profile", userId] as const,
  profileCard: (userId: string) => ["profile-card", userId] as const,
  usernameAvailability: (username: string) => ["username-availability", username] as const,
  activities: (userId: string) => ["activities", userId] as const,
  todayLogs: (userId: string, localDate: string) => ["logs", "today", userId, localDate] as const,
  activityHistory: (userId: string) => ["logs", "history", userId] as const,
  dailyTotals: (userId: string) => ["logs", "daily-totals", userId] as const,
  feed: () => ["feed"] as const,
  feedEntry: (logId: string) => ["feed", "entry", logId] as const,
  comments: (logId: string) => ["comments", logId] as const,
  inbox: (userId: string) => ["inbox", userId] as const,
  yearTotals: (userId: string, year: number) => ["logs", "year-totals", userId, year] as const,
  friends: (userId: string) => ["friends", userId] as const,
  friendRequests: (userId: string) => ["friend-requests", userId] as const,
  profileSearch: (query: string) => ["profile-search", query] as const,
  activityShares: (activityId: string) => ["activity-shares", activityId] as const,
  activeSessions: (userId: string) => ["active-sessions", userId] as const,
  passkeys: (userId: string) => ["passkeys", userId] as const,
  pushSubscription: (userId: string) => ["push-subscription", userId] as const,
  notificationPrefs: (userId: string) => ["notification-prefs", userId] as const,
  invite: (userId: string) => ["invite", userId] as const,
  nudgesSentToday: (userId: string) => ["nudges-sent", userId] as const,
  nudgesReceived: (userId: string) => ["nudges-received", userId] as const,
  friendsActivityToday: (userId: string) => ["friends-activity-today", userId] as const,
  events: (userId: string) => ["events", userId] as const,
  event: (eventId: string) => ["events", "detail", eventId] as const,
  eventPhotos: (eventId: string) => ["event-photos", eventId] as const,
  eventPhotoUrl: (path: string) => ["event-photo-url", path] as const,
} as const;

export const mutationKeys = {
  createLog: ["logs", "create"] as const,
  deleteLog: ["logs", "delete"] as const,
  toggleReaction: ["reactions", "toggle"] as const,
  sendNudge: ["nudges", "send"] as const,
  createActivity: ["activities", "create"] as const,
  updateActivity: ["activities", "update"] as const,
  deleteActivity: ["activities", "delete"] as const,
  replaceShares: ["activity-shares", "replace"] as const,
  sendFriendRequest: ["friends", "request"] as const,
  respondFriendRequest: ["friends", "respond"] as const,
  removeFriend: ["friends", "remove"] as const,
  createEvent: ["events", "create"] as const,
  updateEvent: ["events", "update"] as const,
  deleteEvent: ["events", "delete"] as const,
  respondInvite: ["events", "respond"] as const,
  leaveEvent: ["events", "leave"] as const,
} as const;
