import type { LucideIcon } from 'lucide-react-native'
import {
  Activity,
  Apple,
  Baby,
  Banknote,
  Bed,
  BedDouble,
  Beer,
  BicepsFlexed,
  Bike,
  BookOpen,
  Brain,
  Briefcase,
  BrushCleaning,
  Building2,
  Bus,
  Cake,
  CalendarDays,
  Camera,
  Car,
  Carrot,
  Cat,
  ChartColumn,
  Cigarette,
  CigaretteOff,
  CircleDot,
  Clapperboard,
  ClipboardList,
  Code,
  Coffee,
  Coins,
  Compass,
  CreditCard,
  Dices,
  Dog,
  Dumbbell,
  Egg,
  FileText,
  Film,
  Flame,
  Flower,
  Footprints,
  Gamepad2,
  Gift,
  GlassWater,
  GraduationCap,
  Guitar,
  Hammer,
  Handshake,
  Headphones,
  HeartHandshake,
  HeartPulse,
  Hospital,
  House,
  Infinity,
  Lamp,
  Languages,
  Laptop,
  Library,
  Luggage,
  Mail,
  Map,
  MapPin,
  MessageCircle,
  MicVocal,
  Milk,
  Monitor,
  Moon,
  Mountain,
  Music,
  NotebookPen,
  Palette,
  PartyPopper,
  PawPrint,
  PersonStanding,
  PhoneCall,
  Piano,
  PiggyBank,
  Pill,
  PillBottle,
  Pizza,
  Plane,
  Presentation,
  Puzzle,
  Salad,
  Sandwich,
  Scissors,
  Ship,
  Shirt,
  ShoppingBasket,
  ShoppingCart,
  Smile,
  Sofa,
  Soup,
  Sparkles,
  SprayCan,
  Sprout,
  Star,
  Stethoscope,
  Sunrise,
  Syringe,
  TentTree,
  Thermometer,
  Timer,
  TrainFront,
  Trash2,
  TreePalm,
  Trophy,
  Tv,
  UserPlus,
  Users,
  Utensils,
  Video,
  Volleyball,
  Wallet,
  WashingMachine,
  Waves,
  Weight,
  Wine,
  WineOff,
  Wrench,
} from 'lucide-react-native'

import { DEFAULT_ICON } from './catalog'

export type { CatalogIcon, IconCategory } from './catalog'
export { DEFAULT_ICON, ICON_CATALOG, ICON_CATEGORIES, findIcons, isKnownIcon } from './catalog'

const ICON_COMPONENTS: Record<string, LucideIcon | undefined> = {
  'activity': Activity,
  'apple': Apple,
  'baby': Baby,
  'banknote': Banknote,
  'bed': Bed,
  'bed-double': BedDouble,
  'beer': Beer,
  'biceps-flexed': BicepsFlexed,
  'bike': Bike,
  'book-open': BookOpen,
  'brain': Brain,
  'briefcase': Briefcase,
  'brush-cleaning': BrushCleaning,
  'building-2': Building2,
  'bus': Bus,
  'cake': Cake,
  'calendar-days': CalendarDays,
  'camera': Camera,
  'car': Car,
  'carrot': Carrot,
  'cat': Cat,
  'chart-column': ChartColumn,
  'cigarette': Cigarette,
  'cigarette-off': CigaretteOff,
  'circle-dot': CircleDot,
  'clapperboard': Clapperboard,
  'clipboard-list': ClipboardList,
  'code': Code,
  'coffee': Coffee,
  'coins': Coins,
  'compass': Compass,
  'credit-card': CreditCard,
  'dices': Dices,
  'dog': Dog,
  'dumbbell': Dumbbell,
  'egg': Egg,
  'file-text': FileText,
  'film': Film,
  'flame': Flame,
  'flower': Flower,
  'footprints': Footprints,
  'gamepad-2': Gamepad2,
  'gift': Gift,
  'glass-water': GlassWater,
  'graduation-cap': GraduationCap,
  'guitar': Guitar,
  'hammer': Hammer,
  'handshake': Handshake,
  'headphones': Headphones,
  'heart-handshake': HeartHandshake,
  'heart-pulse': HeartPulse,
  'hospital': Hospital,
  'house': House,
  'infinity': Infinity,
  'lamp': Lamp,
  'languages': Languages,
  'laptop': Laptop,
  'library': Library,
  'luggage': Luggage,
  'mail': Mail,
  'map': Map,
  'map-pin': MapPin,
  'message-circle': MessageCircle,
  'mic-vocal': MicVocal,
  'milk': Milk,
  'monitor': Monitor,
  'moon': Moon,
  'mountain': Mountain,
  'music': Music,
  'notebook-pen': NotebookPen,
  'palette': Palette,
  'party-popper': PartyPopper,
  'paw-print': PawPrint,
  'person-standing': PersonStanding,
  'phone-call': PhoneCall,
  'piano': Piano,
  'piggy-bank': PiggyBank,
  'pill': Pill,
  'pill-bottle': PillBottle,
  'pizza': Pizza,
  'plane': Plane,
  'presentation': Presentation,
  'puzzle': Puzzle,
  'salad': Salad,
  'sandwich': Sandwich,
  'scissors': Scissors,
  'ship': Ship,
  'shirt': Shirt,
  'shopping-basket': ShoppingBasket,
  'shopping-cart': ShoppingCart,
  'smile': Smile,
  'sofa': Sofa,
  'soup': Soup,
  'sparkles': Sparkles,
  'spray-can': SprayCan,
  'sprout': Sprout,
  'star': Star,
  'stethoscope': Stethoscope,
  'sunrise': Sunrise,
  'syringe': Syringe,
  'tent-tree': TentTree,
  'thermometer': Thermometer,
  'timer': Timer,
  'train-front': TrainFront,
  'trash-2': Trash2,
  'tree-palm': TreePalm,
  'trophy': Trophy,
  'tv': Tv,
  'user-plus': UserPlus,
  'users': Users,
  'utensils': Utensils,
  'video': Video,
  'volleyball': Volleyball,
  'wallet': Wallet,
  'washing-machine': WashingMachine,
  'waves': Waves,
  'weight': Weight,
  'wine': Wine,
  'wine-off': WineOff,
  'wrench': Wrench,
}

export function getIconComponent(name: string): LucideIcon {
  return ICON_COMPONENTS[name] ?? ICON_COMPONENTS[DEFAULT_ICON] ?? CircleDot
}
